# Dependencies
markdown:         redcarpet
highlighter:      pygments
highlighter: true


# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Sepanda Pouryahya
tagline:          'Mathematician, Data Scientist, Nonlinear Dynamicist'
description:      'Mathematician, Data Scientist, Nonlinear Dynamicist'
#url:              http://hyde.getpoole.com
url:              /
baseurl:          /

author:
  name:           'Sepanda Pouryahya'
#  url:            https://twitter.com/mdo

paginate:         1

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
  me: https://github.com/sepanda
